# Generated by Django 5.0.4 on 2025-04-13 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المبنى')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('total_floors', models.IntegerField(verbose_name='عدد الطوابق')),
                ('description', models.TextField(blank=True, verbose_name='وصف المبنى')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('shop', 'محل تجاري'), ('office', 'مكتب'), ('apartment', 'شقة'), ('storage', 'مخزن'), ('parking', 'موقف سيارات')], max_length=20, verbose_name='نوع الوحدة')),
                ('unit_number', models.CharField(max_length=20, verbose_name='رقم الوحدة')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المساحة')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري (ريال عماني)')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='مؤجرة؟')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.building', verbose_name='المبنى')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري (ريال عماني)')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الضمان (ريال عماني)')),
                ('contract_file', models.FileField(upload_to='contracts/', verbose_name='ملف العقد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='الشركة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.unit', verbose_name='الوحدة')),
            ],
        ),
    ]
