# Generated by Django 5.0.4 on 2025-04-13 12:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': 'المبني', 'verbose_name_plural': 'المباني'},
        ),
        migrations.AlterModelOptions(
            name='leasecontract',
            options={'ordering': ['-start_date'], 'verbose_name': 'عقد إيجار', 'verbose_name_plural': 'عقود الإيجار'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['building', 'unit_number'], 'verbose_name': 'الوحدة', 'verbose_name_plural': 'الوحدات'},
        ),
        migrations.AddField(
            model_name='building',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='leasecontract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(verbose_name='العنوان التفصيلي'),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_floors',
            field=models.PositiveIntegerField(verbose_name='عدد الطوابق'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company', verbose_name='الشركة المستأجرة'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='contract_file',
            field=models.FileField(upload_to='contracts/%Y/%m/', verbose_name='ملف العقد'),
        ),
        migrations.AlterField(
            model_name='leasecontract',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentals.unit', verbose_name='الوحدة'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rentals.building', verbose_name='المبنى'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('building', 'unit_number')},
        ),
    ]
