# Generated by Django 5.0.4 on 2025-04-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'شركة', 'verbose_name_plural': 'الشركات'},
        ),
    ]
